
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: hmzDB
    ports:
      - '3307:3306'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
